version: '3.8'

services:
  app:
    image: monolith-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/mongo
      SPRING_REDIS_HOST: redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
